package tool;

import model.DataEvent;
import pojo.Customer;
import pojo.Lineitem;
import pojo.Orders;

import java.io.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * 一体化 SQL 生成器：
 * - 默认：生成建库建表语句（DDL）
 * - 带参数：同时解析 input_data_all.csv，生成完整 SQL（DDL + DML）
 */
public class GenSql {

    private static final DateTimeFormatter DATE_FORMAT = DateTimeFormatter.ofPattern("yyyy-MM-dd");

    public static void main(String[] args) throws IOException {


        String inputCsv = "G:/class/IP/FlinkQuery/new_data.csv";
        String outputSql = "G:/class/IP/FlinkQuery/mysql.sql";
        generateFullScript(inputCsv, outputSql);

    }


    private static void generateFullScript(String inputCsv, String outputSql) throws IOException {
        InputParser parser = null;
        try {
            parser = new InputParser(inputCsv);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
        PrintWriter out = new PrintWriter(new FileWriter(outputSql));
        // Step 1: Write DDL
        writeDdl(out);

        // Step 2: Write DML header
        out.println("--\n-- Data operations (INSERT / DELETE)\n--");
        out.println("SET FOREIGN_KEY_CHECKS = 0;");
        out.println();

        // Step 3: Process events
        DataEvent<?> event;
        int count = 0;
        while ((event = parser.nextEvent()) != null) {
            String sql = convertEventToSql(event);
            if (sql != null) {
                out.println(sql);
                count++;
                if (count % 10000 == 0) {
                    System.out.println("Processed " + count + " events...");
                }
            }
        }

        // Step 4: Finalize
        out.println();
        out.println("SET FOREIGN_KEY_CHECKS = 1;");
        out.println("COMMIT;");

        System.out.println("✅ Full SQL script generated: " + outputSql);
        System.out.println("   Total DML statements: " + count);


    }

    // ==================== 写入 DDL ====================
    private static void writeDdl(PrintWriter out) {
        out.println("-- Generated by tool.GenSql");
        out.println("DROP DATABASE IF EXISTS test_flink;");
        out.println("CREATE DATABASE test_flink;");
        out.println("USE test_flink;");
        out.println();

        // customer
        out.println("CREATE TABLE customer (");
        out.println("  c_custkey     BIGINT       NOT NULL PRIMARY KEY,");
        out.println("  c_name        VARCHAR(25)  NOT NULL,");
        out.println("  c_address     VARCHAR(40)  NOT NULL,");
        out.println("  c_nationkey   BIGINT       NOT NULL,");
        out.println("  c_phone       CHAR(15)     NOT NULL,");
        out.println("  c_acctbal     DECIMAL(12,2) NOT NULL,");
        out.println("  c_mktsegment  CHAR(10)     NOT NULL,");
        out.println("  c_comment     VARCHAR(117) NOT NULL");
        out.println(") ENGINE=InnoDB;");
        out.println();

        // orders
        out.println("CREATE TABLE orders (");
        out.println("  o_orderkey      BIGINT        NOT NULL PRIMARY KEY,");
        out.println("  o_custkey       BIGINT        NOT NULL,");
        out.println("  o_orderstatus   CHAR(1)       NOT NULL,");
        out.println("  o_totalprice    DECIMAL(12,2) NOT NULL,");
        out.println("  o_orderdate     DATE          NOT NULL,");
        out.println("  o_orderpriority CHAR(15)      NOT NULL,");
        out.println("  o_clerk         CHAR(15)      NOT NULL,");
        out.println("  o_shippriority  INT           NOT NULL,");
        out.println("  o_comment       VARCHAR(79)   NOT NULL,");
        out.println("  INDEX idx_orders_custkey (o_custkey),");
        out.println("  INDEX idx_orders_orderdate (o_orderdate)");
        out.println(") ENGINE=InnoDB;");
        out.println();

        // lineitem
        out.println("CREATE TABLE lineitem (");
        out.println("  l_orderkey      BIGINT        NOT NULL,");
        out.println("  l_partkey       BIGINT        NOT NULL,");
        out.println("  l_suppkey       BIGINT        NOT NULL,");
        out.println("  l_linenumber    INT           NOT NULL,");
        out.println("  l_quantity      INT           NOT NULL,");
        out.println("  l_extendedprice DECIMAL(12,2) NOT NULL,");
        out.println("  l_discount      DECIMAL(12,2) NOT NULL,");
        out.println("  l_tax           DECIMAL(12,2) NOT NULL,");
        out.println("  l_returnflag    CHAR(1)       NOT NULL,");
        out.println("  l_linestatus    CHAR(1)       NOT NULL,");
        out.println("  l_shipdate      DATE          NOT NULL,");
        out.println("  l_commitdate    DATE          NOT NULL,");
        out.println("  l_receiptdate   DATE          NOT NULL,");
        out.println("  l_shipinstruct  CHAR(25)      NOT NULL,");
        out.println("  l_shipmode      CHAR(10)      NOT NULL,");
        out.println("  l_comment       VARCHAR(44)   NOT NULL,");
        out.println("  PRIMARY KEY (l_orderkey, l_linenumber),");
        out.println("  INDEX idx_lineitem_shipdate (l_shipdate),");
        out.println("  INDEX idx_lineitem_commitdate (l_commitdate),");
        out.println("  INDEX idx_lineitem_receiptdate (l_receiptdate)");
        out.println(") ENGINE=InnoDB;");
        out.println();

        // Foreign keys
        out.println("-- Foreign key constraints");
        out.println("ALTER TABLE orders ADD CONSTRAINT fk_orders_customer");
        out.println("  FOREIGN KEY (o_custkey) REFERENCES customer(c_custkey);");
        out.println();
        out.println("ALTER TABLE lineitem ADD CONSTRAINT fk_lineitem_order");
        out.println("  FOREIGN KEY (l_orderkey) REFERENCES orders(o_orderkey);");
        out.println();
    }

    // ==================== 转换事件为 SQL ====================
    private static String convertEventToSql(DataEvent<?> event) {
        switch (event.getOperation()) {
            case INSERT:
                return generateInsertSql(event);
            case DELETE:
                return generateDeleteSql(event);
            default:
                return null;
        }
    }

    // --- INSERT ---
    private static String generateInsertSql(DataEvent<?> event) {
        Object data = event.getDataObject();
        String table = event.getTableName();

        if ("customer".equals(table) && data instanceof Customer) {
            return buildCustomerInsert((Customer) data);
        } else if ("orders".equals(table) && data instanceof Orders) {
            return buildOrdersInsert((Orders) data);
        } else if ("lineitem".equals(table) && data instanceof Lineitem) {
            return buildLineitemInsert((Lineitem) data);
        }
        return null;
    }

    private static String escapeString(String s) {
        if (s == null) return "NULL";
        return "'" + s.replace("'", "''") + "'";
    }

    private static String buildCustomerInsert(Customer c) {
        return String.format(
                "INSERT INTO customer (c_custkey, c_name, c_address, c_nationkey, c_phone, c_acctbal, c_mktsegment, c_comment) VALUES (%d, %s, %s, %d, %s, %.2f, %s, %s);",
                c.c_custkey,
                escapeString(c.c_name),
                escapeString(c.c_address),
                c.c_nationkey,
                escapeString(c.c_phone),
                c.c_acctbal,
                escapeString(c.c_mktsegment),
                escapeString(c.c_comment)
        );
    }

    private static String buildOrdersInsert(Orders o) {
        return String.format(
                "INSERT INTO orders (o_orderkey, o_custkey, o_orderstatus, o_totalprice, o_orderdate, o_orderpriority, o_clerk, o_shippriority, o_comment) VALUES (%d, %d, %s, %.2f, %s, %s, %s, %d, %s);",
                o.o_orderkey,
                o.o_custkey,
                escapeString(o.o_orderstatus),
                o.o_totalprice,
                escapeString(o.o_orderdate),
                escapeString(o.o_orderpriority),
                escapeString(o.o_clerk),
                o.o_shippriority,
                escapeString(o.o_comment)
        );
    }

    private static String buildLineitemInsert(Lineitem l) {
        return String.format(
                "INSERT INTO lineitem (l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment) VALUES (%d, %d, %d, %d, %d, %.2f, %.2f, %.2f, %s, %s, %s, %s, %s, %s, %s, %s);",
                l.l_orderkey,
                l.l_partkey,
                l.l_suppkey,
                l.l_linenumber,
                l.l_quantity,
                l.l_extendedprice,
                l.l_discount,
                l.l_tax,
                escapeString(l.l_returnflag),
                escapeString(l.l_linestatus),
                escapeString(l.l_shipdate),
                escapeString(l.l_commitdate),
                escapeString(l.l_receiptdate),
                escapeString(l.l_shipinstruct),
                escapeString(l.l_shipmode),
                escapeString(l.l_comment)
        );
    }

    // --- DELETE ---
    private static String generateDeleteSql(DataEvent<?> event) {
        Object data = event.getDataObject();
        String table = event.getTableName();

        if ("customer".equals(table) && data instanceof Customer) {
            long key = ((Customer) data).c_custkey;
            return String.format("DELETE FROM customer WHERE c_custkey = %d;", key);
        } else if ("orders".equals(table) && data instanceof Orders) {
            long key = ((Orders) data).o_orderkey;
            return String.format("DELETE FROM orders WHERE o_orderkey = %d;", key);
        } else if ("lineitem".equals(table) && data instanceof Lineitem) {
            Lineitem l = (Lineitem) data;
            return String.format("DELETE FROM lineitem WHERE l_orderkey = %d AND l_linenumber = %d;",
                    l.l_orderkey, l.l_linenumber);
        }
        return null;
    }
}